import { BLANK_PDF } from '@pdfme/common';
import { generate } from '@pdfme/generator';

// Default text field properties
const baseText = { type: 'text', alignment: 'left', fontSize: 11, lineHeight: 1.5, position: { x: 15, y: 0 }, width: 180, height: 10, fontColor: '#2D1F3D' };

export const downloadTarotPDF = async (cards, analysis, userData) => {
  const template = {
    basePdf: BLANK_PDF,
    schemas: [
      [
        { ...baseText, name: 'title', position: { x: 10, y: 15 }, width: 190, height: 15, fontSize: 28, alignment: 'center', fontColor: '#6C63FF' },
        { ...baseText, name: 'subtitle', position: { x: 10, y: 32 }, width: 190, height: 10, fontSize: 12, alignment: 'center' },
        
        { ...baseText, name: 'themeTitle', position: { x: 15, y: 50 }, fontSize: 16, fontColor: '#6C63FF' },
        { ...baseText, name: 'themeText', position: { x: 15, y: 60 }, height: 25 },
        
        { ...baseText, name: 'pastTitle', position: { x: 15, y: 90 }, fontSize: 14, fontColor: '#a78bfa' },
        { ...baseText, name: 'pastText', position: { x: 15, y: 100 }, height: 30 },
        
        { ...baseText, name: 'presentTitle', position: { x: 15, y: 135 }, fontSize: 14, fontColor: '#ffd700' },
        { ...baseText, name: 'presentText', position: { x: 15, y: 145 }, height: 30 },
        
        { ...baseText, name: 'futureTitle', position: { x: 15, y: 180 }, fontSize: 14, fontColor: '#8b5cf6' },
        { ...baseText, name: 'futureText', position: { x: 15, y: 190 }, height: 30 },
        
        { ...baseText, name: 'adviceTitle', position: { x: 15, y: 225 }, fontSize: 16, fontColor: '#6C63FF' },
        { ...baseText, name: 'adviceText', position: { x: 15, y: 235 }, height: 40 },
        
        { ...baseText, name: 'footer', position: { x: 10, y: 280 }, width: 190, fontSize: 9, alignment: 'center', fontColor: '#888888' }
      ]
    ]
  };

  const inputs = [{
    title: 'Tarot Reading Analysis',
    subtitle: `Seeker: ${userData.firstName}   |   D.O.B: ${userData.dob}   |   Date: ${new Date().toLocaleDateString()}`,
    themeTitle: `Overall Theme: ${analysis.overallTheme.primary}`,
    themeText: analysis.overallTheme.description + '\n\n' + analysis.combinedMessage,
    pastTitle: `Past: ${analysis.positions.past.card} (${analysis.positions.past.orientation})`,
    pastText: analysis.positions.past.context + '\n' + analysis.positions.past.meaning,
    presentTitle: `Present: ${analysis.positions.present.card} (${analysis.positions.present.orientation})`,
    presentText: analysis.positions.present.context + '\n' + analysis.positions.present.meaning,
    futureTitle: `Future: ${analysis.positions.future.card} (${analysis.positions.future.orientation})`,
    futureText: analysis.positions.future.context + '\n' + analysis.positions.future.meaning,
    adviceTitle: 'Actionable Guidance',
    adviceText: analysis.actionableAdvice.map(a => `• ${a}`).join('\n\n'),
    footer: 'Generated by Rachna Astrology - For self-reflection and entertainment purposes'
  }];

  try {
    const pdf = await generate({ template, inputs });
    triggerDownload(pdf, `tarot_reading_${userData.firstName}.pdf`);
  } catch (error) {
    console.error("Error generating PDF:", error);
    alert("Could not generate PDF. Please check console for errors.");
  }
};

export const downloadBirthCardPDF = async (birthCards, userData, majorArcanaData) => {
  const template = {
    basePdf: BLANK_PDF,
    schemas: [
      [
        { ...baseText, name: 'title', position: { x: 10, y: 15 }, width: 190, height: 15, fontSize: 28, alignment: 'center', fontColor: '#6C63FF' },
        { ...baseText, name: 'subtitle', position: { x: 10, y: 32 }, width: 190, height: 10, fontSize: 12, alignment: 'center' },
        
        { ...baseText, name: 'lifePath', position: { x: 15, y: 55 }, fontSize: 16, alignment: 'center', width: 180 },
        
        { ...baseText, name: 'pTitle', position: { x: 15, y: 80 }, fontSize: 18, fontColor: '#6C63FF' },
        { ...baseText, name: 'pDesc', position: { x: 15, y: 92 }, height: 60 },
        
        { ...baseText, name: 'sTitle', position: { x: 15, y: 160 }, fontSize: 18, fontColor: '#6C63FF' },
        { ...baseText, name: 'sDesc', position: { x: 15, y: 172 }, height: 60 },
        
        { ...baseText, name: 'footer', position: { x: 10, y: 280 }, width: 190, fontSize: 9, alignment: 'center', fontColor: '#888888' }
      ]
    ]
  };

  const getCard = (id) => majorArcanaData.find(c => c.id === id);
  const pCard = getCard(birthCards.personalityCardId);
  const sCard = getCard(birthCards.soulCardId);

  const inputs = [{
    title: 'Your Cosmic Birth Cards',
    subtitle: `Seeker: ${userData.firstName}   |   D.O.B: ${userData.dob}`,
    lifePath: `Life Path Number: ${birthCards.lifePathNumber}`,
    pTitle: `Personality Card: ${pCard ? pCard.name : ''}`,
    pDesc: pCard ? `What the world sees and how you interact with it.\n\n${pCard.upright}\n\nKey themes: ${pCard.keywords.join(', ')}` : 'N/A',
    sTitle: `Soul Card: ${sCard ? sCard.name : ''}`,
    sDesc: sCard ? `Your inner self, soul purpose, and deeper truth.\n\n${sCard.upright}\n\nKey themes: ${sCard.keywords.join(', ')}` : 'N/A',
    footer: 'Generated by Rachna Astrology - For self-reflection and entertainment purposes'
  }];

  try {
    const pdf = await generate({ template, inputs });
    triggerDownload(pdf, `birth_cards_${userData.firstName}.pdf`);
  } catch (error) {
    console.error("Error generating PDF:", error);
    alert("Could not generate PDF.");
  }
};

const triggerDownload = (pdfBuffer, filename) => {
  const blob = new Blob([pdfBuffer.buffer || pdfBuffer], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
